# Generated by Django 5.2 on 2025-05-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('id',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('id',), 'verbose_name': 'Арендуемый товар', 'verbose_name_plural': 'Арендуемые товары'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Получен', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
